"""Build and send the post-fix notification email.

The email is assembled entirely from local bugpilot artifacts (result_summary.md
and jira_summary.md) and sent over SMTP using credentials supplied through the
environment. bugpilot never hardcodes SMTP secrets and never commits, pushes, or
updates Jira as part of sending this notification.
"""

from __future__ import annotations

import io
import json
import smtplib
import ssl
import urllib.error
import urllib.request
from dataclasses import dataclass
from email.generator import BytesGenerator
from email.message import EmailMessage
from email.utils import formataddr, parseaddr
from pathlib import Path
from urllib.parse import urlencode

from .config import EmailConfig, GraphConfig, issue_dir, load_config
from .jira import sanitize_comment_text

GRAPH_TOKEN_URL = "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"
GRAPH_SENDMAIL_URL = "https://graph.microsoft.com/v1.0/users/{sender}/sendMail"
GRAPH_SCOPE = "https://graph.microsoft.com/.default"

MAX_SECTION_CHARS = 4000
MAX_BODY_CHARS = 60000
_NOT_AVAILABLE = "Not available in local artifacts."


@dataclass
class EmailDraft:
    issue_key: str
    subject: str
    body: str


@dataclass
class EmailSendResult:
    issue_key: str
    sent: bool
    recipients: tuple[str, ...]
    skipped_reason: str | None = None


class EmailSendError(Exception):
    """Raised when an SMTP send fails. The message never contains credentials."""


def build_email_draft(repo_root: Path, issue_key: str) -> EmailDraft:
    target = issue_dir(repo_root, issue_key)
    result_summary = _read(target / "result_summary.md")
    jira_summary = _read(target / "jira_summary.md")

    summary_line = _section(jira_summary, "## Summary") or _section(result_summary, "## Issue")
    summary_line = _first_meaningful_line(summary_line)

    original_problem = _section(jira_summary, "## Description") or _NOT_AVAILABLE
    root_cause = _section(result_summary, "## Root Cause Summary") or _NOT_AVAILABLE
    fix_summary = _section(result_summary, "## Fix Summary") or _NOT_AVAILABLE
    diff_summary = _section(result_summary, "## Diff Summary") or _NOT_AVAILABLE
    test_summary = _section(result_summary, "## Test Summary") or _NOT_AVAILABLE

    subject = f"[bugpilot] {issue_key} fix ready to commit"
    if summary_line:
        subject = f"{subject}: {summary_line[:80]}"

    link_line = _jira_link(repo_root, issue_key)
    body = (
        "bugpilot bug fix notification\n"
        "===========================\n\n"
        "Automated notification generated at the commit decision point.\n"
        "Review before committing. bugpilot did NOT commit, push, merge, open a PR,\n"
        "or update Jira.\n\n"
        "## Jira Item\n"
        f"{issue_key}" + (f" — {summary_line}" if summary_line else "") + "\n"
        + (f"{link_line}\n" if link_line else "")
        + "\n"
        "## Original Problem\n"
        f"{_cap(original_problem)}\n\n"
        "## Bug Cause / Root Cause\n"
        f"{_cap(root_cause)}\n\n"
        "## Changes Made\n"
        f"{_cap(fix_summary)}\n\n"
        "## Changed Files / Diff\n"
        f"{_cap(diff_summary)}\n\n"
        "## Tests\n"
        f"{_cap(test_summary)}\n\n"
        "--\n"
        f"Generated by bugpilot from local .ai/{issue_key}/ artifacts.\n"
    )
    body = _cap(sanitize_comment_text(body), MAX_BODY_CHARS)
    return EmailDraft(issue_key=issue_key, subject=subject, body=body)


def send_notification(config: EmailConfig, draft: EmailDraft) -> EmailSendResult:
    if not config.is_configured:
        missing = ", ".join(config.missing_fields())
        return EmailSendResult(
            issue_key=draft.issue_key,
            sent=False,
            recipients=config.recipients,
            skipped_reason=f"Email not configured. Missing: {missing}.",
        )

    invalid = [addr for addr in config.recipients if not _looks_like_email(addr)]
    if invalid or not _looks_like_email(config.sender or ""):
        bad = ", ".join(invalid or [config.sender or "(empty)"])
        raise EmailSendError(f"Invalid email address configured: {bad}")

    message = _build_message(config, draft)
    try:
        _deliver(config, message)
    except (smtplib.SMTPException, OSError) as exc:
        # Surface the error class/reason, never the credentials.
        raise EmailSendError(f"SMTP send failed: {type(exc).__name__}: {exc}") from exc

    return EmailSendResult(
        issue_key=draft.issue_key,
        sent=True,
        recipients=config.recipients,
    )


def render_eml(draft: EmailDraft, sender: str | None = None, recipients: tuple[str, ...] = ()) -> bytes:
    """Render the draft as a standalone RFC 822 .eml file.

    Works without SMTP configuration: From/To headers are filled in only when
    available so the file can be opened in Outlook (which sends over its own
    modern-auth channel, sidestepping SMTP entirely).
    """
    message = _message(draft, sender, recipients)
    buffer = io.BytesIO()
    BytesGenerator(buffer, policy=message.policy).flatten(message)
    return buffer.getvalue()


def send_via_graph(
    graph_config: GraphConfig,
    draft: EmailDraft,
    sender: str | None,
    recipients: tuple[str, ...],
) -> EmailSendResult:
    """Send the notification through Microsoft Graph (client-credentials flow).

    Uses HTTPS only, so it works when the tenant disables SMTP client auth and
    when outbound port 25 is blocked. Requires an app registration with the
    application permission Mail.Send (admin-consented).
    """
    if not graph_config.is_configured or not sender or not recipients:
        missing = ", ".join(graph_config.missing_fields())
        if not sender:
            missing = (missing + ", HRS_AI_EMAIL_FROM").lstrip(", ")
        if not recipients:
            missing = (missing + ", HRS_AI_EMAIL_TO").lstrip(", ")
        return EmailSendResult(
            issue_key=draft.issue_key,
            sent=False,
            recipients=recipients,
            skipped_reason=f"Graph email not configured. Missing: {missing}.",
        )

    invalid = [addr for addr in recipients if not _looks_like_email(addr)]
    if invalid or not _looks_like_email(sender):
        bad = ", ".join(invalid or [sender])
        raise EmailSendError(f"Invalid email address configured: {bad}")

    token = _graph_token(graph_config)
    _graph_send_mail(token, sender, recipients, draft)
    return EmailSendResult(issue_key=draft.issue_key, sent=True, recipients=recipients)


def _graph_token(graph_config: GraphConfig) -> str:
    data = urlencode(
        {
            "client_id": graph_config.client_id,
            "client_secret": graph_config.client_secret,
            "scope": GRAPH_SCOPE,
            "grant_type": "client_credentials",
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        GRAPH_TOKEN_URL.format(tenant=graph_config.tenant_id),
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        # Do not echo the request body (it carries the client secret).
        raise EmailSendError(f"Graph token request failed: HTTP {exc.code}") from exc
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise EmailSendError(f"Graph token request failed: {type(exc).__name__}: {exc}") from exc
    token = payload.get("access_token") if isinstance(payload, dict) else None
    if not token:
        raise EmailSendError("Graph token response did not contain an access token.")
    return str(token)


def _graph_send_mail(token: str, sender: str, recipients: tuple[str, ...], draft: EmailDraft) -> None:
    body = json.dumps(
        {
            "message": {
                "subject": draft.subject,
                "body": {"contentType": "Text", "content": draft.body},
                "toRecipients": [{"emailAddress": {"address": addr}} for addr in recipients],
            },
            "saveToSentItems": True,
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        GRAPH_SENDMAIL_URL.format(sender=sender),
        data=body,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            response.read()
    except urllib.error.HTTPError as exc:
        detail = _graph_error_detail(exc)
        raise EmailSendError(f"Graph sendMail failed: HTTP {exc.code}{detail}") from exc
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise EmailSendError(f"Graph sendMail failed: {type(exc).__name__}: {exc}") from exc


def _graph_error_detail(exc: urllib.error.HTTPError) -> str:
    try:
        payload = json.loads(exc.read().decode("utf-8"))
        code = payload.get("error", {}).get("code")
        return f" ({code})" if code else ""
    except Exception:
        return ""


def _build_message(config: EmailConfig, draft: EmailDraft) -> EmailMessage:
    return _message(draft, config.sender, config.recipients)


def _message(draft: EmailDraft, sender: str | None, recipients: tuple[str, ...]) -> EmailMessage:
    message = EmailMessage()
    message["Subject"] = draft.subject
    if sender:
        message["From"] = formataddr(("bugpilot", sender))
    if recipients:
        message["To"] = ", ".join(recipients)
    message.set_content(draft.body)
    return message


def _deliver(config: EmailConfig, message: EmailMessage) -> None:
    host = config.host or ""
    if config.use_ssl:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL(host, config.port, timeout=30, context=context) as server:
            _authenticate_and_send(server, config, message)
        return
    with smtplib.SMTP(host, config.port, timeout=30) as server:
        if config.use_starttls:
            server.starttls(context=ssl.create_default_context())
        _authenticate_and_send(server, config, message)


def _authenticate_and_send(server: smtplib.SMTP, config: EmailConfig, message: EmailMessage) -> None:
    if config.uses_auth:
        server.login(config.username or "", config.password or "")
    server.send_message(message)


def _jira_link(repo_root: Path, issue_key: str) -> str:
    base_url = load_config(repo_root).jira_base_url
    if not base_url:
        return ""
    return f"Link: {base_url.rstrip('/')}/browse/{issue_key}"


def _read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def _section(markdown: str, heading: str) -> str:
    if not markdown:
        return ""
    lines = markdown.splitlines()
    try:
        start = lines.index(heading) + 1
    except ValueError:
        return ""
    collected: list[str] = []
    for line in lines[start:]:
        if line.startswith("## ") and collected:
            break
        collected.append(line)
    text = "\n".join(collected).strip()
    return "" if text in {"", "TBD"} else text


def _first_meaningful_line(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and stripped != "TBD":
            return stripped
    return ""


def _cap(text: str, limit: int = MAX_SECTION_CHARS) -> str:
    text = text.strip() or _NOT_AVAILABLE
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + "\n\n[truncated by bugpilot]"


def _looks_like_email(address: str) -> bool:
    name, addr = parseaddr(address)
    del name
    return "@" in addr and "." in addr.split("@")[-1] and " " not in addr
